tdc_qa_homepage:
    pattern:  /{start}/{max}
    defaults:
        _controller: tdcQABundle:Default:index
        start: 1
        max: 10
    requirements:
        start: \d+
        max: \d+

tdc_qa_view:
    pattern: /question/{id}
    defaults: { _controller: tdcQABundle:Default:view }

tdc_qa_ask:
    pattern: /ask
    defaults: { _controller: tdcQABundle:Default:ask }

tdc_qa_answer:
    pattern: /answer/{id}
    defaults: { _controller: tdcQABundle:Default:answer }

tdc_qa_tagged:
    pattern: /tagged/{tag}/{start}/{max}
    defaults:
        _controller: tdcQABundle:Default:tagged
        tag: "all"
        start: 1
        max: 10
    requirements:
        tag: \w+
        start: \d+
        max: \d+
