parameters:
    tdc_qa.example.class: tdc\QABundle\Service\QAService

services:
    tdc.qaservice:
        class: %tdc_qa.example.class%
        arguments: [@doctrine]
        #arguments: [@service_id, "plain_value", %parameter%]
