tdc\QABundle\Entity\Question:
    type: entity
    table: question
    id:
        id:
            type: integer
            generator: { strategy : AUTO }
    fields:
        text:
            type: text
        created:    
            type: datetime
        updated:
            type: datetime
        views:
            type: integer
    manyToOne:
        user:
            targetEntity: tdc\UserBundle\Entity\User
            inversedBy: questions
    oneToMany:
        answers:
            targetEntity: Answer
            mappedBy: question
    manyToMany:
        tags:
            targetEntity: QuestionTag
            inversedBy: questions
            joinTable:
                name: question_tags
                joinColumns:
                    question_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
