tdc\UserBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator: { strategy : AUTO }
    fields:
        name:
            type: string
            length: 255
            nullable: true
        lastname:
            type: string
            length: 255
            nullable: true
    oneToMany:
        ratings:
            targetEntity: \tdc\VideoBundle\Entity\Rating
            mappedBy: user
