tdc\UserBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator: { strategy : AUTO }
    fields:
        name:
            type: string
            length: 255
            nullable: true
        lastname:
            type: string
            length: 255
            nullable: true
    oneToMany:
        ratings:
            targetEntity: \tdc\VideoBundle\Entity\Rating
            mappedBy: user
        questions:
            targetEntity: \tdc\QABundle\Entity\Question
            mappedBy: user
        answers:
            targetEntity: \tdc\QABundle\Entity\Answer
            mappedBy: user
    oneToOne:
        subscription:
            targetEntity: Subscription
            mappedBy: user_subscription

