tdc\VideoBundle\Entity\Category:
    type: entity
    table: category
    id:
        id:
            type: integer
            generator: { strategy : AUTO }
    fields:
        name:
            type: string
            length: 100
        summary:
            type: string
            length: 250
            nullable: true
        description:
            type: text
            nullable: true
        status:
            type: integer
            size: 3
            default: 0
            nullable: true
    oneToMany:
        children:
            targetEntity: Category
            mappedBy: parent
    manyToOne:
        parent:
            targetEntity: Category
            inversedBy: children
