tdc\VideoBundle\Entity\Video:
    type: entity
    table: video
    id:
        id:
            type: integer
            generator: { strategy : AUTO }
    fields:
        name:
            type: string
            length: 100
        author:
            type: string
            length: 100
        summary:
            type: string
            length: 250
            nullable: true
        filepath:
            type: string
            length: 250
        description:
            type: text
            nullable: true
        toc:
            type: text 
            nullable: true
        status:
            type: integer
            size: 3
            default: 0
            nullable: true
        views:
            type: integer
            nullable: true
        icon:
            type: string
            nullable: true
            length: 250
        trt:
            type: string
            nullable: true
            lenght: 30

    manyToMany:
        categories:
            targetEntity: Category
            inversedBy: videos
            joinTable:
                name: video_category
                joinColumns:
                    video_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    category_id:
                        referencedColumnName: id
    oneToMany:
        ratings:
            targetEntity: Rating
            mappedBy: video
        questions:
            targetEntity: tdc\QABundle\Entity\Question
            mappedBy: user
        answers:
            targetEntity: tdc\QABundle\Entity\Answer 
            mappedBy: user
