tdc_admin:
    pattern:  /
    defaults: { _controller: tdcAdminBundle:Admin:index }

tdc_admin_videos:
    pattern:  /videos/{start}/{max}
    defaults: 
        _controller: tdcAdminBundle:Admin:video
        start: 1
        max: 10
    requirements:
        start: \d+
        max: \d+

tdc_admin_video_view:
    pattern:  /video/{id}
    defaults: { _controller: tdcAdminBundle:Admin:videoView }

tdc_admin_video_edit:
    pattern:  /video/edit/{id}
    defaults: { _controller: tdcAdminBundle:Admin:videoEdit }
