tdc_front_homepage:
    pattern:  /
    defaults: { _controller: tdcFrontEndBundle:Front:index }

tdc_front_catalog_item:
    pattern: /catalog/{entity}/{id}/{start}/{max}
    defaults:
        _controller: tdcFrontEndBundle:Front:catalogItem
        entity: "video"
        start: 1
        max: 10
    requirements:
        id: \d+
        start: \d+
        max: \d+

tdc_front_catalog_list:
    pattern: /catalog/{entity}/{start}/{max}
    defaults:
        _controller: tdcFrontEndBundle:Front:catalogList
        entity: "video" 
        start: 1
        max: 10
    requirements:
        entity: \w+
        start: \d+
        max: \d+

tdc_front_about:
    pattern: /about
    defaults: { _controller: tdcFrontEndBundle:Front:about }

tdc_front_faq:
    pattern: /faq
    defaults: { _controller: tdcFrontEndBundle:Front:faq }

