tdc_front_homepage:
    pattern:  /
    defaults: { _controller: tdcFrontEndBundle:Front:index }

tdc_front_catalog:
    pattern: /catalog/{id}
    defaults: { _controller: tdcFrontEndBundle:Front:catalog, id:-1 }
    requirements:
        id: \d+

tdc_front_category:
    pattern: /category/{id} 
    defaults: { _controller: tdcFrontEndBundle:Front:category, id:-1 }
    requirements:
        id: \d+

tdc_front_about:
    pattern: /about
    defaults: { _controller: tdcFrontEndBundle:Front:about }

tdc_front_faq:
    pattern: /faq
    defaults: { _controller: tdcFrontEndBundle:Front:faq }

tdc_logedin_home:
    pattern: /home
    defaults: { _controller: tdcFrontEndBundle:Front:home }
