parameters:
#    tdc_front_end.example.class: tdc\FrontEndBundle\Example

services:
#    tdc_front_end.example:
#        class: %tdc_front_end.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
