parameters:
    tdc_front_end.service.class: tdc\FrontEndBundle\Service\FrontEndService

services:
    tdc.FrontEndService:
        class: %tdc_front_end.service.class%
        arguments: [@doctrine]
