parameters:
#    tdc_user.example.class: tdc\UserBundle\Example

services:
#    tdc_user.example:
#        class: %tdc_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
